<?php

/**
 * Class {{ controller_name }}
 * Generated by AdminBuildr
 */
class {{ controller_name }} extends {{ base_controller_name }}
{
	/**
	 * @access Role
	 */
	public function indexAction()
	{
		error_reporting(0);	// 暂时不能处理关联不到的数据而显示的错误
		$condition = Strings::filter($_GET);
		$result = {{model_name}}::search($condition);

		$count = $result['count'];
		$items = $result['items'];
		$data = array(
			'count' => $count,
			'items' => $items, 
			'i' => $condition,
			'item_has_checkbox' => {{ item_has_checkbox }},
			'item_has_operator' => {{ item_has_operator }},
			'headers' => {{model_name}}::headers()
			);
		$views = array('name' => '查看列表', 'template' => '{{lower(model_name)}}-report/index');
		parent::showPager($_GET['__pager_current'], $result['page_count']);
		parent::showTabViews($views, '查看', $data);
	}

	public function exportAction($type)
	{
		// TODO: Header
		if ($type == 'excel') {
			$this->exportToExcelFile();
		} else if ($type == 'csv') {
			$this->exportToCsvFile();
		}
	}

	private function exportToCsvFile()
	{

	}

	private function exportToExcelFile()
	{
		
	}
}