<div class="form-horizontal">
    <span>Forms Creator</span>

    <br>
    <!-- Region select -->
    <div class="control-group">
        <div widget-class="RegionSelector" widget-id="province" mode="province" class="pull-left margin-right-20">
            <select field="">
                <option value="-1">请选择省</option>
                {% for p in china_region_provinces %}
                <option value="{{p['sys_region_id']}}">{{p['sys_region_name']}}</option>
                {% endfor %}
            </select>
        </div>
        <div widget-class="RegionSelector" widget-id="city" mode="city" class="pull-left margin-right-20" listen-to="province">
            <select field="">
            </select>
        </div>
        <div widget-class="RegionSelector" widget-id="county" mode="county" class="pull-left" listen-to="city">
            <select field="">
            </select>
        </div>
    </div>


    <div class="control-group">
        <label class="control-label">上传</label>

        <div id="uploader1" class="controls" widget-class="FileUploader">
            <div class="thumbnail" style="width: 120px; height: 120px;margin-bottom: 10px">

            </div>
            <div>
                <div class="picker">选择文件</div>
                <a class="btn btn-default upload" style="display: none">开始上传</a>
            </div>
            <input type="hidden" class="filepath" name="file_field">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">上传</label>

        <div id="uploader2" class="controls" widget-class="FileUploader">
            <div class="thumbnail" style="width: 120px; height: 120px;margin-bottom: 10px">

            </div>
            <div>
                <div class="picker">选择文件</div>
                <a class="btn btn-default upload" style="display: none">开始上传</a>
            </div>
            <input type="hidden" class="filepath" name="file_field">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label">上传</label>
        <div id="uploader3" class="controls" widget-class="FileUploader">
            <div class="thumbnail" style="width: 120px; height: 120px;margin-bottom: 10px">

            </div>
            <div>
                <div class="picker">选择文件</div>
                <a class="btn btn-default upload" style="display: none">开始上传</a>
            </div>
            <input type="hidden" class="filepath" name="file_field">
        </div>
    </div>
</div>