<style>
    .AdvancedSearch .chzn-container .chzn-results li {
        display: list-item;
    }

</style>

<div class="form-horizontal">
    <span>Forms Creator</span>

    <form>
        <input type="hidden" name="__pager_current"/>
    </form>
    <br>
    <!-- Advanced search input -->
    <div class="control-group">
        {{ tag_html('file_upload', ['label':'简历文件地址', 'upload_url':'abFile/upload', 'field':'resume']) }}
    </div>

    <div class="control-group">
        {{ tag_html('img_upload', ['label':'照片文件地址', 'upload_url':'abFile/upload', 'field':'photo']) }}
    </div>

    <div class="control-group">
        {{ text_field("tagType":"abTag", 'label':'用户名', 'field':'username', 'value':'1') }}
    </div>

    <div class="DTP">
        <label class="control-label">{{label}}</label>
        <div class="controls">
            <input class="m-wrap m-ctrl-medium date-picker" readonly
                   placeholder="{{placeholder}}" size="16" type="text"
                   name="{{field}}" value="{{value}}"/>
            <input class="m-wrap m-ctrl-medium date-picker" readonly
                   placeholder="{{placeholder}}" size="16" type="text"
                   name="{{field}}" value="{{value}}"/>
        </div>
    </div>



    {% if show_pager is defined and show_pager == true%}
    {% include "common/pager.phtml" %}
    {% endif %}
</div>