<div>
    <div class="row-fluid">

        <div widget-class="EntryEditList" widget-id="action-edit-list">
            <table class="manage table table-striped table-bordered table-hover table-full-width dataTable">
                <thead>
                <tr>
                    <td>常量类名</td>
                    <td>操作</td>
                </tr>
                <tr class="entry-template" style="display: none">
                    <td><input class="name" type="text"/></td>
                    <td>
                        <a class="btn blue property small" data-toggle="modal">属性</a>
                        <a class="btn blue del small" data-toggle="modal">放弃</a>
                    </td>
                </tr>
                </thead>
                <tbody>
                {% for i in classNames %}
                <tr>
                    <td><input class="name" type="text" value="{{i['className']}}"/></td>

                    <td><a class="btn blue property small" data-toggle="modal">编辑</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <a class="btn blue add" data-toggle="modal">增加</a>
        </div>

    </div>
</div>