<div>
    <form action="kxAdminRole/editAdminRole" method="POST">
        <div class="form-horizontal">
            <input type="hidden" name="role_id" value="{{i['role_id']}}"/>
            <div class="control-group">
                <div class="Text">
                    <label class="control-label">名称</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="name" value="{{i['name']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>


            <div class="control-group">
                <div class="Text">
                    <label class="control-label">名称</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="remark" value="{{i['remark']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>

        </div>
        <div class="clearfix margin-bottom-10">
            <a class="btn grey" href="javascript:history.back()">返回 <i class="m-icon-swapleft m-icon-white"></i></a>
            <a type="submit" class="btn blue">保存 <i class="m-icon-swapright m-icon-white"></i></a>
        </div>
    </form>

</div>