<div class="span12">


    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
            <td><b>Controller</b></td>
            <td><b>Action</b></td>

            </thead>
            {% for controller, actions in controllerNodes %}
            <tr>
                <td>
                    {{ controller }}
                </td>

                <td style="padding:0px">
                    <table class="table table-striped table-bordered table-hover table-full-width dataTable"
                           style="margin: 0px;border: 0px">
                        {% for action in actions %}
                        <tr node_id="{{action['node_id']}}">
                            <td controller="{{ controller }}"
                                action="{{action['action']}}"
                                width="200px">
                                <a href="{{ controller }}/{{action['action']}}">{{ controller }}/{{action['action']}}</a>
                            </td>
                            <td>
                                <span>{{ action['name'] }}</span>
                            </td>
                            <td width="100px">
                                <input type="checkbox">
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </td>


            </tr>
            {% endfor %}
        </table>
    </div>

    <button id="sync-button" class="btn blue btn-block">更新 <i class="m-icon-swapright m-icon-white"></i></button>

</div>
