<div>
    <a href="javascript:void(0)" class="btn purple-stripe">当前角色: {{role_name}}</a>


    <div id="menu_group_operator" class="clearfix margin-top-10 margin-bottom-10">
        <div class="control-group toolbar">
            <a class="btn icn-only blue moveUp" direct="u">
                上移 <i class="m-icon-swapup m-icon-white"></i>
            </a>
            <a class="btn icn-only blue moveDown" direct="d">
                下移 <i class="m-icon-swapdown m-icon-white"></i>
            </a>
        </div>
    </div>

    <div widget-class="EntryEditList" widget-id="entry-edit-list">
        <table class="table table-striped table-bordered table-hover table-full-width dataTable" id="menu_group_table">
            <thead>
            <tr>
                <td>菜单组ID</td>
                <td>菜单组名称</td>
                <td>说明</td>
                <td>操作</td>
            </tr>
            <tr class="entry-template entry" style="display: none">
                <td><span class="value" type="text"></span></td>
                <td><input class="name" type="text"/></td>
                <td><input class="display" type="text"/></td>
                <td>
                    <a class="btn blue del small" data-toggle="modal">删除</a>
                </td>
            </tr>
            </thead>
            <tbody>
            {% for m in menus %}
            <tr class="entry">
                <td><span class="value" type="text">{{m['menu_id']}}</span></td>
                <td><input class="name" type="text" value="{{m['menu_name']}}"/></td>
                <td><input class="display" type="text" value="{{m['menu_desc']}}"/></td>
                <td>
                    <a class="btn blue del small" data-toggle="modal">删除</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <a class="btn blue add" data-toggle="modal">增加</a>
    </div>
    <br>

    <div style="clear: both"></div>
    <a class="btn blue" onclick="updateMenuGroups()">更新</a>

</div>