<div>
    <div>
        <div id="group-template"
             class="alert"
             style="display:none">

            <button class="close" data-dismiss="alert"></button>

            <strong><input class="name"/></strong>

            <div style="float:right">
                <a href='javascript:void(0)' class="moveUp" direct="u">上移</a>
                <a href='javascript:void(0)' class="moveDown" direct="d">下移</a>
            </div>
            <div style="clear: both"></div>
        </div>

    </div>
    <div id="group-edit-pane" class="span6">

    </div>
    <div style="clear: both"></div>
    <div id="group-edit" class="span6">
        <a class="btn blue" onclick="addNewMenuGroup()">新增</a>
        <a class="btn blue" onclick="updateAllMenuGroups()">更新</a>
    </div>

</div>