<script>

    function operate(a) {
        var action = a.attr('action');
        var target = a.attr('target');
        window.location.href = action + "/" + target;
    }

    function deleteItem(a) {
        var action = a.attr('action');
        var target = a.attr('target');
        // TODO: Confirm to edit
        var deleteUrl = action + "/" + target;
        $.getJSON(deleteUrl, {}, function (data) {
            console.log(data);
        })
    }

    $(function(){

        // operators delegates
        $('td.item-operators').delegate('a', 'click', function () {
            var a = $(this);
            var operator = a.attr('operator');
            if (operator == 'editNode' || operator == 'listAdminUser' || operator == 'editMenu') {
                operate(a);
            } else if (operator == 'delete') {
                deleteItem(a);
            }
        });

        $('#check_all').click(function () {
            var checked = $(this).parent().hasClass('checked');
            if (checked) {
                $('td.check_item span').addClass('checked');
            } else {
                $('td.check_item span').removeClass('checked');
            }
        });
    });

</script>