<div>
    <div>
        <select id="select-role">
            {% for role in roles %}
            <option value="{{role['role_id']}}"
                    {%if current==role['role_id'] %}selected{% endif %}>{{role['name']}}
            </option>
            {% endfor %}
        </select>
        <button id="select-change-button" class="btn blue btn-block">查看 <i class="m-icon-swapright m-icon-white"></i></button>
    </div>
    <table class="table table-striped table-bordered table-hover table-full-width dataTable">
        <thead>
        <tr>
            <td>ID</td>
            <td>用户名</td>
            <td>昵称</td>
            <td>Email</td>
            <td>电话</td>
            <td>修改时间</td>
        </tr>
        </thead>

        <tbody>
        {% for user in users %}
        <tr>
            <td>{{user['admin_uid']}}</td>
            <td>{{user['username']}}</td>
            <td>{{user['nickname']}}</td>
            <td>{{user['email']}}</td>
            <td>{{user['phone']}}</td>
            <td>{{user['update_time']}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>