<div>
    <a href="javascript:void(0)" class="btn purple-stripe">当前角色: {{role['name']}}</a>
    <table class="table table-striped table-bordered table-hover table-full-width dataTable">
        <thead>
        <tr>
            <td>ID</td>
            <td>用户名</td>
            <td>昵称</td>
            <td>Email</td>
            <td>电话</td>
            <td>修改时间</td>
        </tr>
        </thead>

        <tbody>
        {% for user in users %}
        <tr>
            <td>{{user['admin_uid']}}</td>
            <td>{{user['username']}}</td>
            <td>{{user['nickname']}}</td>
            <td>{{user['email']}}</td>
            <td>{{user['phone']}}</td>
            <td>{{user['update_time']}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-info" href="kxAdminRole/createAdminUser/{{role_id}}">新增管理员</a>
</div>