<div id="responsive" class="modal hide fade" tabindex="-1" data-width="760">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h3>@@Responsive</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span6">
                <h4>Some Input</h4>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
            </div>
            <div class="span6">
                <h4>Some More Input</h4>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
                <p><input type="text" class="span12 m-wrap"></p>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn">Close</button>
        <button type="button" class="btn blue">Save changes</button>
    </div>
</div>
