<div class="span10 booking-search">

    <div class="clearfix margin-bottom-10">
        <label>请输入MySQL连接</label>

        <div class="input-icon left">
            <i class="icon-map-marker"></i>
            <input class="m-wrap span12" type="text" placeholder="host:port:username:password">
        </div>
    </div>

    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <label>请输入前缀</label>

            <div class="input-icon left">
                <i class="icon-map-marker"></i>
                <input id="model_prefix" class="m-wrap span8" type="text" placeholder="prefix_name">
            </div>
        </div>

        <div class="margin-bottom-10 pull-left">
            <label>请输入表名称</label>

            <div class="input-icon left">
                <i class="icon-map-marker"></i>
                <input id="table_name" class="m-wrap span12" type="text" placeholder="table_name">
            </div>
        </div>
    </div>

    <div>
        <button id="load-model-button" class="btn blue btn-block">加载 <i class="m-icon-swapright m-icon-white"></i></button>
        <table id="fields_action_table" class="table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
                <tr>
                    <td>字段</td>
                    <td title="列表页字段行为">模式</td>
                    <td title="字段显式名称">名称</td>
                    <td title="新增页字段行为">列表</td>
                    <td title="新增页字段行为">新增</td>
                    <td title="编辑页字段行为">编辑</td>
                    <td title="编辑页字段行为">查找</td>
                </tr>
                <tr id="fields_action_row_template" style="display: none">
                    <td field="field">
                        <b><span class="field_name"></span></b>
                        <br>
                        <span class="field_type"></span>
                    </td>

                    <td field="field_mode">
                        <select name="field_mode">
                            <option value="fk">关联ID</option>
                            <option value="number">数字</option>
                            <option value="text">文本</option>
                            <option value="richtext">富文本</option>
                            <option value="date">日期</option>
                            <option value="time">时间</option>
                            <option value="datetime">日期+时间</option>
                            <option value="enum">枚举</option>
                            <option value="img">图片</option>
                            <option value="file">文件链接</option>
                        </select>
                    </td>
                    <td field="field_text">
                        <input name="field_text"/>
                    </td>
                    <td field="hide_in_list">
                        <select name="hide_in_list">
                            <option value="0">显示</option>
                            <option value="1">隐藏</option>
                        </select>
                    </td>
                    <td field="hide_in_create">
                        <select name="hide_in_create">
                            <option value="0">显示</option>
                            <option value="1">隐藏</option>
                        </select>
                    </td>
                    <td field="hide_in_update">
                        <select name="hide_in_update">
                            <option value="0">显示</option>
                            <option value="1">隐藏</option>
                        </select>
                    </td>
                    <td title="search_action">
                        <select name="hide_in_create">
                            <option value="0">不支持查找</option>
                            <option value="1">精确匹配</option>
                            <option value="2">模糊匹配</option>
                            <option value="3">区间</option>
                            <option value="4">离散集合</option>
                        </select>
                    </td>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
    <hr>
    <!-- 保存/提交相关 -->
    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="commit_support" type="checkbox" name="remember" value="1"/>支持提交
        </div>

        <div class="margin-bottom-10 margin-right-20 pull-left">
            <select id="commit_field_select" name="commit_field">
                <option value="0">选择表达是否提交的字段</option>

            </select>
        </div>
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="commit_field_value" type="text" name="delete_value" placeholder="该字段值表达已经提交"/>
        </div>
    </div>
    <hr>
    <!-- 删除相关 -->
    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="delete_support" type="checkbox" name="remember" value="1"/>支持删除
        </div>

        <div class="margin-bottom-10 margin-right-20 pull-left">
            <select id="delete_field_select" name="delete_field">
                <option value="0">选择表达是否删除的字段</option>

            </select>
        </div>
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="delete_field_value" type="text" name="delete_value" placeholder="该字段值表达已经删除"/>
        </div>
    </div>


    <div class="clearfix margin-bottom-10"></div>

    <button id="preview-button" class="btn blue btn-block">预览 <i class="m-icon-swapright m-icon-white"></i></button>


</div>