<div class="span12">

    <div>生成文件</div>
    <div>
        <table class="file-preview table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
                <tr id="files_template" style="display: none">
                    <td><span></span></td>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>

    <div>
        <span>测试</span>
        <a href="{{ test_list_url }}" target="_blank">打开列表</a>
    </div>


    <button id="generate-button" class="btn blue btn-block">生成 <i class="icon-ok m-icon-white"></i></button>
</div>