{% include "abreport/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>数据源表</span></td>
                <td>
                    <div class="controls">
                        <select class="span8 table-name" name="tablename" data-placeholder="Select a database table" tabindex="1">
                            <option value="-">选择被关联的表</option>
                            {% for table_name in table_names %}
                            <option value="{{table_name}}">{{table_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </td>

            </tr>

            <tr>
                <td>用于关联的字段</td>
                <td>
                    <select id="field_name_for_fk" name="fieldname" class="span8 field-names related-field" data-placeholder="Select a field" tabindex="1">
                    </select>
                </td>
            </tr>

            <tr>
                <td>用于显示的字段</td>
                <td>
                    <select id="field_name_for_display" name="fieldname" class="span8 field-names display-field" data-placeholder="Select a field" tabindex="1">
                    </select>
                </td>
            </tr>


            </tbody>
        </table>


    </div>
</div>