<div>

    <table class="table table-striped table-bordered table-hover table-full-width dataTable">
        <thead>
        <tr>
            {% if item_has_checkbox %}
            <td><input id='check_all' type="checkbox"/></td>
            {% endif %}

            {% for index, header in headers %}
            <td>{{ header }}</td>
            {% endfor %}
            {% if item_has_operator %}
            <td>操作</td>
            {% endif %}
        </tr>
        </thead>

        <tbody>
        {% for item in items %}
        <tr>
            {% if item_has_checkbox %}
            <td class='check_item'><input type="checkbox"/></td>
            {% endif %}
            {% for index, header in headers %}
            <td>
                {{ item[index] }}
            </td>
            {% endfor %}
            {% if item_has_operator %}
            <td class="item-operators">
                {% for o in item_operators %}
                <a href="javascript:void(0)"
                   operator="{{o['operator']}}"
                   target="{{item[target_field]}}"
                   action="{{o['action']}}"><span>{{o['name']}}</span></a>
                {% endfor %}
            </td>
            {% endif %}
        {% endfor %}
        </tr>
        </tbody>
    </table>
</div>