<div>
    <form action="kxAdminUser/edit" method="POST">
        <div class="form-horizontal">
            <input type="hidden" name="admin_uid" value="{{i['admin_uid']}}"/>
            <div class="control-group">
                <div class="Text">
                    <label class="control-label">用户名</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="username" value="{{i['username']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <div class="Text">
                    <label class="control-label">昵称</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="nickname" value="{{i['nickname']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <div class="Text">
                    <label class="control-label">角色</label>

                    <div class="controls">
                        <select class="m-wrap small" name="role_id">
                            {% for role in roles %}
                            <option value="{{role['role_id']}}"
                                    {% if i['role_id'] == role['role_id'] %}selected{% endif %}>
                                {{role['name']}} ({{role['remark']}})
                            </option>
                            {% endfor %}
                        </select>

                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <div class="Text">
                    <label class="control-label">电子邮件</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="email" value="{{i['email']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>


            <div class="control-group">
                <div class="Text">
                    <label class="control-label">电话</label>

                    <div class="controls">
                        <input type="text" placeholder="" class="m-wrap small" name="phone" value="{{i['phone']}}">
                        <span class="help-inline"></span>
                    </div>
                </div>
            </div>

        </div>
        <div class="clearfix margin-bottom-10">
            <a class="btn grey" href="javascript:history.back()">返回 <i class="m-icon-swapleft m-icon-white"></i></a>
            <a type="submit" class="btn blue">保存 <i class="m-icon-swapright m-icon-white"></i></a>
        </div>
    </form>

</div>