<div>

    <table class="table table-striped table-bordered table-hover table-full-width dataTable">
        <thead>
        <tr>
            <td>ID</td>
            <td>用户名</td>
            <td>昵称</td>
            <td>Email</td>
            <td>电话</td>
            <td>修改时间</td>
            <td>操作</td>
        </tr>
        </thead>

        <tbody>
        {% for user in users %}
        <tr>
            <td>{{user['admin_uid']}}</td>
            <td>{{user['username']}}</td>
            <td>{{user['nickname']}}</td>
            <td>{{user['email']}}</td>
            <td>{{user['phone']}}</td>
            <td>{{user['update_time']}}</td>
            <td class="item-operators">
                {% for o in item_operators %}
                <a href="javascript:void(0)"
                   operator="{{o['operator']}}"
                   target="{{user[target_field]}}"
                   action="{{o['action']}}"><span>{{o['name']}}</span></a>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-info" href="kxAdminUser/create/{{role_id}}">新增管理员</a>
</div>