{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>文件上传位置</span></td>
                <td>
                    <div class="controls">
                        <input type="text" name="upload_path"/>
                    </div>
                </td>

            </tr>

            <tr>
                <td>文件名规则</td>
                <td>
                    <input type="text" name="filename_pattern"/>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
