{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>图片上传位置</span></td>
                <td>
                    <div class="controls">
                        <input/>
                    </div>
                </td>

            </tr>

            <tr>
                <td>文件名规则</td>
                <td>
                    <input type="text"/>
                    <span>时间可选规则：{yyyy-mm-dd}, {unix_timestamp}, {random}, {md5}, {origin}, {wxh}</span>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
