{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
            <tr>
                <td>值</td>
                <td>显示名称</td>
                <td>删除</td>
            </tr>

            </thead>
            <tbody>
                <tr>
                    <td><input type="text"/></td>
                    <td><input type="text"/></td>
                    <td><a class="btn blue del small" data-toggle="modal">删除</a></td>
                </tr>

                <tr>
                    <td><input type="text"/></td>
                    <td><input type="text"/></td>
                    <td><a class="btn blue del small" data-toggle="modal">删除</a></td>
                </tr>
            </tbody>
        </table>


    </div>

</div>
