{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>时间类型</span></td>
                <td>
                    <div class="controls">
                        <select type="text" name="type">
                            <option value="date">日期</option>
                            <option value="datetime">日期+时间</option>
                            <option value="create_time">创建时间</option>
                            <option value="update_time">修改时间</option>
                        </select>
                    </div>
                </td>

            </tr>

            </tbody>
        </table>
    </div>
</div>
