{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">
    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td>分组信息</td>
                <td>
                    <input type="text" placeholder="分组唯一标识"/>

                </td>
            </tr>
            <tr>
                <td>组件含义</td>
                <td>
                    <select class="region-type" name="region_type">
                        <option value="province">省</option>
                        <option value="city">市</option>
                        <option value="county">区</option>
                    </select>
                    <input class="group-name" type="text" placeholder="分组显示名称"/>
                </td>
            </tr>
            <tr>
                <td>组件ID</td>
                <td>
                    <input type="text" placeholder="widget-id"/>
                    <span class="help-inline" style="margin-top: -6px;">如果该组件需要被侦听，请填写widget-id</span>
                </td>
            </tr>
            <tr>
                <td>侦听组件ID</td>
                <td>
                    <input type="text" placeholder="widget-id to listen"/>
                    <span class="help-inline"></span>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
