{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>图片上传位置</span></td>
                <td>
                    <div class="controls">
                        <select type="text" name="upload_path">
                            <option value="__UPLOAD_URL__">临时选择(查找生成文件中的__UPLOAD_URL__)</option>
                        </select>
                    </div>
                    <a class="btn refresh">刷新</a>
                </td>

            </tr>

            </tbody>
        </table>
    </div>
</div>
