<div class="row-fluid">
    <div class="span6">
        <h4>Some Input</h4>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
    </div>
    <div class="span6">
        <h4>Some More Input</h4>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
    </div>
</div>