<div class="row-fluid">
    <div class="span6">
        <h4>Value</h4>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
    </div>
    <div class="span6">
        <h4>Display Name</h4>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
        <p><input type="text" class="span12 m-wrap"></p>
    </div>
</div>