{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>

            <tr>
                <td>字段含义</td>
                <td>
                    <select id="region_type_select" name="region_type">
                        <option value="1">省</option>
                        <option value="2">市</option>
                        <option value="3">区</option>
                    </select>
                </td>
            </tr>

            <tr>
                <td>区域字段</td>
                <td>
                    <select id="region_id_select" name="region_id_select"></select>
                </td>
            </tr>

            </tbody>
        </table>


    </div>

</div>
