{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>时间类型</span></td>
                <td>
                    <div class="controls">
                        <select type="text" name="type">
                            <option value="date">日期</option>
                            <option value="datetime">日期+时间</option>

                        </select>
                    </div>
                </td>

            </tr>

            <tr>
                <td><span>是否当前时间</span></td>
                <td>
                    <div class="controls">
                        <input type="checkbox" name="is_current"/> <!-- TODO -->
                        <span>如果选中则不能手工录入或编辑</span>
                    </div>
                </td>

            </tr>

            </tbody>
        </table>
    </div>
</div>
