{% include "abmodule/dialog-common.phtml" %}
<div class="row-fluid">

    <div>
        <table class="table text table-striped table-bordered table-hover table-full-width dataTable">

            <tbody>
                <tr>
                    <td>类型</td>
                    <td>
                        <select type="text" name="type">
                            <option value="" selected>任意文本(默认)</option>
                            <option value="digits">整数</option>
                            <option value="number">浮点数字</option>
                            <option value="mobile">手机号码(+86)</option>
                            <option value="email">电子邮件</option>
                            <option value="url">网址URL</option>
                            <option value="creditcard">信用卡号</option>
                        </select>
                    </td>

                </tr>

                <tr>
                    <td>最小长度</td>
                    <td><input type="text" placeholder="不填写表示无限制" name="minlength" value=""/></td>
                </tr>
                <tr>
                    <td>最大长度</td>
                    <td><input type="text" placeholder="不填写表示无限制" name="maxlength" value=""/></td>
                </tr>

                <tr class="number-min">
                    <td>最小值</td>
                    <td><input class="min" placeholder="不填写表示无限制" name="min" type="text"/></td>
                </tr>

                <tr class="number-max">
                    <td>最小值</td>
                    <td><input class="max" placeholder="不填写表示无限制" name="max" type="text"/></td>
                </tr>

            </tbody>
        </table>


    </div>

</div>
