<div class="span12">

    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20">
            <label>请输入CURD标题</label>

            <div class="input-icon left">
                <i class="icon-map-marker"></i>
                <input id="module_title" class="m-wrap span6" type="text" placeholder="CURD Title">
            </div>
        </div>
    </div>

    <div class="clearfix margin-bottom-10">

        <div class="control-group">
            <label class="control-label">请选择数据库表名称</label>

            <div class="controls">
                <select id="table_name" class="span6 chosen" data-placeholder="Select a database table" tabindex="1">
                    <option value="kx_user">User</option>
                    {% for table_name in table_names %}
                    <option value="{{table_name}}">{{table_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="margin-left-20" style="margin-top: -1px;float: left">
                <!-- BUG: the div with float:left is a dynamic element -->
                <button id="load-model-button" class="btn blue btn-block">加载 <i class="m-icon-swapright m-icon-white"></i></button>
            </div>
        </div>

    </div>

    <div class="clearfix margin-bottom-10">
        <div class="control-group toolbar">
            <a class="btn icn-only blue moveUp" direct="u">
                上移 <i class="m-icon-swapup m-icon-white"></i>
            </a>
            <a class="btn icn-only blue moveDown" direct="d">
                下移 <i class="m-icon-swapdown m-icon-white"></i>
            </a>
        </div>
    </div>


    <div>
        <table id="fields_action_table" class="table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
                <tr>
                    <td>字段</td>
                    <td title="列表页字段行为">模式</td>
                    <td title="字段显式名称">名称</td>
                    <td title="是否处理">是否处理</td>
                    <td title="是否必填">是否必填</td>
                    <td title="编辑页字段行为">操作</td>
                </tr>
                <tr id="fields_action_row_template" style="display: none">

                    <td field="field">
                        <b><span class="field_name"></span></b>
                        <br>
                        <span class="field_type"></span>
                    </td>

                    <td field="field_mode">
                        <select name="field_mode">
                            <option value="text">文本/数字</option>
                            <option value="richtext">富文本</option>
                            <option value="datetime">日期时间</option>
                            <option value="enum">枚举</option>
                            <option value="boolean">布尔</option>
                            <option value="image">图片</option>
                            <option value="file">文件链接</option>
                            <option value="region">省、市、区</option>
                            <option value="fk">关联ID</option>
                            <option value="link">链接</option>
                            <option value="group">多值组合</option>
                        </select>
                    </td>
                    <td field="field_text">
                        <input name="field_text"/>
                    </td>
                    <td>
                        <select field="handle">
                            <option value="1">处理</option>
                            <option value="0">不处理</option>
                        </select>
                    </td>
                    <td>
                        <select field="required">
                            <option value="1">必填</option>
                            <option value="0">选填</option>
                        </select>
                    </td>
                    <td>

                        <a class="btn blue more" data-toggle="modal">更多</a>
                    </td>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
    <hr>
    <!-- 保存/提交相关 -->
    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="commit_support" type="checkbox" name="remember" value="1"/>支持提交
        </div>

        <div class="margin-bottom-10 margin-right-20 pull-left">
            <select id="commit_field_select" name="commit_field">
                <option value="0">选择表达是否提交的字段</option>

            </select>
        </div>
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="commit_field_value" type="text" name="delete_value" placeholder="该字段值表达已经提交"/>
        </div>
    </div>
    <hr>
    <!-- 删除相关 -->
    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="delete_support" type="checkbox" value="1"/>支持软删除
        </div>

        <div class="margin-bottom-10 margin-right-20 pull-left">
            <select id="delete_field_select" name="delete_field">
                <option value="0">选择表达是否删除的字段</option>

            </select>
        </div>
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="delete_field_value" type="text" placeholder="该字段值表达已经删除"/>
        </div>
    </div>
    <hr>
    <!-- 导出相关 -->
    <div class="clearfix">
        <div class="margin-bottom-10 margin-right-20 pull-left">
            <input id="export_support" type="checkbox" value="1"/>支持导出
        </div>

        <div class="margin-bottom-10 margin-right-20 pull-left">
            <select id="export_support_type" >
                <option value="0">全部</option>
                <option value="1">CSV文件(.csv)</option>
                <option value="2">Excel文件(.xls)</option>
            </select>
        </div>

    </div>


    <!-- 暂时去掉前缀功能支持
    <div class="margin-bottom-10 margin-right-20">
        <label>请输入模块前缀</label>

        <div class="input-icon left">
            <i class="icon-map-marker"></i>
            <input id="model_prefix" class="m-wrap span6" type="text" placeholder="Module prefix name">
        </div>
    </div>
    -->

    <div class="clearfix margin-bottom-10">
        <button id="preview-button" class="btn blue btn-block">预览 <i class="m-icon-swapright m-icon-white"></i></button>
    </div>

</div>

