<div class="span12">

    <div>生成文件</div>
    <div>
        <table class="file-preview table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
                <tr id="files_template" style="display: none">
                    <td><span></span></td>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>

    <div>
        <a id="test_list_url" href="#" target="_blank">点击演示结果</a>
    </div>

    {# TODO: 增加简单的版本管理，防止错误覆盖原来的文件 #}
    <button id="generate-button" class="btn blue btn-block">生成 <i class="icon-ok m-icon-white"></i></button>
</div>