<div class="span12">
    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <thead>
                <td><b>Controller</b></td>
                <td><b>Action</b></td>
            </thead>
            {% for controller, actions in controllers %}
            <tr>
                <td>
                    {{ controller }}
                </td>

                <td style="padding:0px">
                    <table class="actions table table-striped table-bordered table-hover table-full-width dataTable"
                            style="margin: 0px;border: 0px">
                        {% for action in actions %}
                    <tr node_id="{{action['node_id']}}">
                        <td title="{{ controller }}/{{action['action']}}"
                            controller="{{ controller }}"
                            action="{{action['action']}}"
                            width="200px">
                            <span {% if action['brand_new'] %}style="color:green"{% endif%}>
                                {{action['action']}}
                            </span>

                        </td>
                        <td>
                            <input value="{{action['name']}}">
                        </td>
                    </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <button id="sync-button" class="btn blue btn-block">更新 <i class="m-icon-swapright m-icon-white"></i></button>

</div>
