<div>
    <div class="row-fluid">

        <div widget-class="EntryEditList" widget-id="action-edit-list">
            <table class="table table-striped table-bordered table-hover table-full-width dataTable">
                <thead>
                <tr><td>文件上传URL</td><td>文件上传路径</td><td>删除</td></tr>
                <tr class="entry-template" style="display: none">
                    <td><input class="value" type="text"/></td>
                    <td><input class="name" type="text"/></td>
                    <td>
                        <a class="btn blue property small" data-toggle="modal">属性</a>
                        <a class="btn blue del small" data-toggle="modal">放弃</a>
                    </td>
                </tr>
                </thead>
                <tbody>
                {% for i in actions %}
                <tr>
                    <td><input class="value" type="text" value="{{i['action']}}" readonly/></td>
                    <td><input class="name" type="text" readonly/></td>
                    <td><a class="btn blue property small" data-toggle="modal">属性</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <a class="btn blue add" data-toggle="modal">增加</a>
        </div>

    </div>
</div>