
<script>

    $class('SettingsDialog', Dialog, {
        template: "kxfile/settings",
        show: function(e) {
            var domNode = this.showDialog(e);
            domNode.delegate('input[name]', 'input', function(){
                var this_ = $(this);
                var v = this_.val();
                this_.parent().find('span a').text(v + '/upload');
            });
        },

        onOk: function () {
            return true;
        }
    });

    $(function() {
        $('table.manage').delegate('a.property', 'click', function(){
            var d = new SettingsDialog();
            d.show();
        });
    })
</script>