<div widget-class="Breadcrumb" widget-id="breadcrumb">
    <ul class="breadcrumb" style="background-color: #FFFFCC;">
        <li class="home level1">
            <i class="icon-home"></i>
            <a href="#"></a>
            <i class="icon-angle-right"></i>
        </li>

        {% for index, breadcrumb in breadcrumbs %}
        <li class="level{{index+2}}">
            <a href="#">{{ breadcrumb }}</a>
            {% if index + 1 < breadcrumbs|length %}
            <i class="icon-angle-right"></i>
            {% endif %}
        </li>

        {% endfor %}
        <!-- 4 levels at most -->
        {% if breadcrumb_with_date_picker %}
        <li class="pull-right no-text-shadow">
            <div id="dashboard-report-range" class="dashboard-date-range tooltips no-tooltip-on-touch-device responsive"
                 data-tablet="" data-desktop="tooltips" data-placement="top" data-original-title="选择日期">
                <i class="icon-calendar"></i>
                <span></span>
                <i class="icon-angle-down"></i>
            </div>
        </li>
        {% endif %}
    </ul>
</div>