<div id="{% block dialog_id %}{% endblock %}" class="modal hide fade" tabindex="-1" data-width="760">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h3>{% block dialog_title %}{% endblock %}</h3>
    </div>
    <div class="modal-body">
        {{ partial(dialog['content']) }}
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn">{% block dialog_cancel %}{% endblock %}</button>
        <button type="button" class="btn blue">{% block dialog_ok %}{% endblock %}</button>
    </div>
</div>
