<script>

    var validateArgs = {
        showErrors: function(e) {
            console.log(3, e)
        },

        submitHandler: function(form)
        {
            $(form).ajaxSubmit({
                url: $options.action,
                success: function(data) {
                    if ($options.handler) {
                        $options.handler.apply(null, [data, form]);
                    }
                }
            });
        }
    };

    var validator = $('#the-form').validate($.extend(validateArgs, $options));
</script>