<!-- header.phtml -->
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse navbar-fixed-top">
	<!-- BEGIN TOP NAVIGATION BAR -->
	<div class="navbar-inner">
		<div class="container-fluid">
			<!-- BEGIN LOGO -->
			<!--<a class="brand" href="index.html">
			<img src="media/image/logo2.png" alt="logo"/>
			</a>-->
			<a>
			<img src="media/image/zhuhai_logo2.png" style="width: 40px;height: 40px; margin-top: 5px; margin-left: 2px" alt="logo"/>
			</a>
			<span style="display:block; font-family:'微软雅黑'; font-weight: bold; font-size: 18px;color:#ffffff; margin-top: -30px; margin-left: 55px">北京市辐射环境监测系统</span>
			<!-- END LOGO -->
			<!-- BEGIN RESPONSIVE MENU TOGGLER -->
			<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
			<img src="media/image/menu-toggler.png" alt="" />
			</a>          
			<!-- END RESPONSIVE MENU TOGGLER -->            
			<!-- BEGIN TOP NAVIGATION MENU -->              
			<ul class="nav pull-right">
				<!-- BEGIN NOTIFICATION DROPDOWN -->   
				<li class="dropdown" id="header_notification_bar">
                    <!--
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<i class="icon-warning-sign"></i>
					<span class="badge">0</span>
					</a>
					-->

					<ul class="dropdown-menu extended notification">
                        <!--
						<li>
							<p>You have 14 new notifications</p>
						</li>
						<li>
							<a href="#">
							<span class="label label-success"><i class="icon-plus"></i></span>
							New user registered. 
							<span class="time">Just now</span>
							</a>
						</li>
						<li>
							<a href="#">
							<span class="label label-important"><i class="icon-bolt"></i></span>
							Server #12 overloaded. 
							<span class="time">15 mins</span>
							</a>
						</li>
						<li>
							<a href="#">
							<span class="label label-warning"><i class="icon-bell"></i></span>
							Server #2 not respoding.
							<span class="time">22 mins</span>
							</a>
						</li>
						<li>
							<a href="#">
							<span class="label label-info"><i class="icon-bullhorn"></i></span>
							Application error.
							<span class="time">40 mins</span>
							</a>
						</li>
						<li>
							<a href="#">
							<span class="label label-important"><i class="icon-bolt"></i></span>
							Database overloaded 68%. 
							<span class="time">2 hrs</span>
							</a>
						</li>
						<li>
							<a href="#">
							<span class="label label-important"><i class="icon-bolt"></i></span>
							2 user IP blocked.
							<span class="time">5 hrs</span>
							</a>
						</li>
						<li class="external">
							<a href="#">See all notifications <i class="m-icon-swapright"></i></a>
						</li>
						-->
					</ul>

				</li>
				<!-- END NOTIFICATION DROPDOWN -->


				<!-- BEGIN USER LOGIN DROPDOWN -->
				<li class="dropdown user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">

					<img alt="" src="" />


					<span class="username">系统管理员</span>
					<i class="icon-angle-down"></i>
					</a>
					<ul class="dropdown-menu">
						<li><a href="extra_profile.html"><i class="icon-user"></i>&nbsp;&nbsp;设置</a></li>
						<li class="divider"></li>
						<li><a id="signOut"><i class="icon-key"></i>&nbsp;&nbsp;退出</a></li>
					</ul>
				</li>
				<!-- END USER LOGIN DROPDOWN -->
			</ul>
			<!-- END TOP NAVIGATION MENU --> 
		</div>
	</div>
	<!-- END TOP NAVIGATION BAR -->
</div>