<script src="media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
<script src="media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="media/js/highcharts.js" type="text/javascript"></script>

<script src="media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="media/js/bootstrap.min.js" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="media/js/excanvas.min.js"></script>
<script src="media/js/respond.min.js"></script>
<![endif]-->
<script src="media/js/jquery.slimscroll.min.js" type="text/javascript"></script>

<script src="media/js/jquery.blockui.min.js" type="text/javascript"></script>
<script src="media/js/jquery.cookie.min.js" type="text/javascript"></script>
<script src="media/js/jquery.uniform.min.js" type="text/javascript" ></script>
<script src="media/js/chosen.jquery.min.js" type="text/javascript" ></script>
<script src="media/js/jquery.flot.js" type="text/javascript"></script>
<script src="media/js/jquery.flot.resize.js" type="text/javascript"></script>
<script src="media/js/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="media/js/date.js" type="text/javascript"></script>
<script src="media/js/daterangepicker.js" type="text/javascript"></script>
<script src="media/js/jquery.gritter.js" type="text/javascript"></script>
<script src="media/js/fullcalendar.min.js" type="text/javascript"></script>
<script src="media/js/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script src="media/js/jquery.sparkline.min.js" type="text/javascript"></script>

<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="media/js/app.js" type="text/javascript"></script>
<script src="media/js/index.js" type="text/javascript"></script>
<script src="media/js/md5.js" type="text/javascript"></script>

<script src="media/js/jquery.backstretch.min.js" type="text/javascript"></script>
<script src="media/js/lock.js"></script>

<script src="active-web/config.js" type="text/javascript"></script>
<script src="active-web/classes.js" type="text/javascript"></script>
<script src="media/widgets/form-fields.js" type="text/javascript"></script>

<script src="media/js/bootstrap-modal.js" type="text/javascript" ></script>
<script src="media/js/bootstrap-modalmanager.js" type="text/javascript" ></script>
<script src="media/js/ui-modals.js" type="text/javascript"></script>

<script type="text/javascript" src="media/js/bootstrap-wysihtml5.js"></script>

<script type="text/javascript" src="media/js/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="media/js/jquery.multi-select.js"></script>
<script src="media/js/form-components.js"></script>
<script type="text/javascript" src="media/js/select2.min.js"></script>
<script>
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        UIModals.init();
        Index.init();

        //Index.initJQVMAP();   // init index page's custom scripts
        Index.initCalendar();   // init index page's custom scripts
        Index.initCharts();     // init index page's custom scripts
        Index.initChat();
        Index.initMiniCharts();
        Index.initDashboardDaterange();
        Index.initIntro();

        Lock.init();






        activeWeb();



        jQuery.download = function(url, data, method){
            // 获取url和data
            if( url && data ){
                // data 是 string 或者 array/object
                data = typeof data == 'string' ? data : jQuery.param(data);
                // 把参数组装成 form的 input
                var inputs = '';
                jQuery.each(data.split('&'), function(){
                    var pair = this.split('=');
                    inputs+='<input type="hidden" name="'+ pair[0] +'" value="'+ pair[1] +'" />';
                });
                // request发送请求
                jQuery('<form action="'+ url +'" method="'+ (method||'post') +'">'+inputs+'</form>')
                        .appendTo('body').submit().remove();
            };
        };

    });
</script>