<!-- sidebar.phtml -->
<div class="page-sidebar nav-collapse collapse" widget-class="Sidebar" widget-id="sidebar">
    <!-- BEGIN SIDEBAR MENU -->
    <ul class="page-sidebar-menu">
        <li>
            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            <div class="sidebar-toggler hidden-phone"></div>
            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        </li>
        {% for menu_group in menu_groups %}
        <li class="start {% if menu_group['active']==true %}active{% endif %}" >
            <a href="javascript:void(0)">
                <i class="icon-home"></i>
                <span class="title">{{menu_group['name']}}</span>
                <span class="selected"></span>
            </a>
            <ul class="sub-menu">
                {% for menu in menu_group['sub_menus'] %}
				<li>
					<a href="{{menu['url']}}">{{menu['name']}}</a>
				</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
    <!-- END SIDEBAR MENU -->
</div>