<!-- index/style action -->
<meta charset="utf-8" params="<?php echo $p1 ?>" />
<base href="/" />
<title>AdminBuildr</title>

<meta content="width=device-width, initial-scale=1.0" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="media/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="media/css/custom.css" rel="stylesheet" type="text/css"/>
<link href="media/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="media/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
<link href="media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="media/css/style-metro.css" rel="stylesheet" type="text/css"/>
<link href="media/css/style.css" rel="stylesheet" type="text/css"/>
<link href="media/css/style2.css" rel="stylesheet" type="text/css"/>
<link href="media/css/style-responsive.css" rel="stylesheet" type="text/css"/>
<link href="media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>
<link href="media/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link href="media/css/chosen.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->

<!-- BEGIN PAGE LEVEL STYLES -->
<link href="media/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>
<link href="media/css/daterangepicker.css" rel="stylesheet" type="text/css" />
<link href="media/css/fullcalendar.css" rel="stylesheet" type="text/css"/>
<link href="media/css/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>

<!-- END PAGE LEVEL STYLES -->
<link rel="shortcut icon" href="media/image/favicon.ico" />