<div>
    <div class="row-fluid">

        <div widget-class="FileUploaderList" widget-id="action-edit-list">
            <table class="manage table table-striped table-bordered table-hover table-full-width dataTable">
                <thead>
                <tr>
                    <td>文件上传URL</td>
                    <td>文件名格式</td>
                    <td>子目录格式</td>
                    <td>操作</td>
                </tr>
                <tr class="entry-template" style="display: none">
                    <td><span class="value" type="text"></span></td>
                    <td><span class="name" type="text"></span></td>
                    <td><span class="name" type="text"></span></td>
                    <td>
                        <a class="btn blue property small" data-toggle="modal">属性</a>
                        <a class="btn blue del small" data-toggle="modal">放弃</a>
                    </td>
                </tr>
                </thead>
                <tbody>
                {% for i in uploads %}
                <tr>
                    <td><span value="{{i['url']}}" >{{i['url']}}</span></td>
                    <td><span value="{{i['filename_pattern']}}">{{i['filename_pattern']}}</span></td>
                    <td><span value="{{i['subdir_pattern']}}">{{i['subdir_pattern']}}</span></td>
                    <td><a class="btn blue property small" data-toggle="modal">属性</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <a class="btn blue add" data-toggle="modal">增加</a>
        </div>

    </div>
</div>