<script>
    // 上传Action设置对话框
    $class('SettingsDialog', Dialog, {

        template: "abfile/settings",

        controller: null,

        filenamePattern: null,

        subdirPattern: null,

        show: function(e) {
            var this_ = this;
            var domNode = this.showDialog(e);
            domNode.delegate('input[name]', 'input', function(){
                var this_ = $(this);
                var v = this_.val();
                this_.parent().find('span a').text(v + '/upload');
            });

            domNode.delegate('.btn-build, .btn-build-force', 'click', function () {
                var overwrite = $(this).attr('overwrite');
                this_.build(domNode, overwrite);
            });
        },

        build: function(domNode, overwrite) {
            var this_ = this;
            var controller = domNode.find('[name=name]').val(),
                    filenamePattern = domNode.find('[name=filename_pattern]').val(),
                    subdirPattern = domNode.find('[name=subdir_pattern]').val();

            var $post = {
                overwrite: overwrite,
                controller: controller,
                // path: domNode.find('[name=path]').val(),
                filename_pattern: filenamePattern,
                subdir_pattern: subdirPattern
            };
            $.post('abFile/build', $post, function(data){
                var r = data.toJson();
                console.log(r);
                if (r.error == 0) {
                    this_.controller = controller;
                    this_.filenamePattern = filenamePattern;
                    this_.subdirPattern = subdirPattern;
                } else if (r.error == -2) {
                    // TODO: Post flag means can overwrite the Controller file
                }
            });
        },

        onOk: function () {
            if (this.controller) {
                window.location.reload();
            }
            return true;
        }
    });

    $class('FileUploaderList', EntryEditList, {

        onAddEntry: function() {
            var d = new SettingsDialog();
            d.show();
        }
    });


    $(function() {
        $('table.manage').delegate('a.property', 'click', function(){
            var d = new SettingsDialog();
            d.show();
        });

    })
</script>