<div class="row-fluid">
    <div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable">
            <tbody>
            <tr>
                <td><span>文件上传URL</span></td>
                <td>
                    <div class="controls">
                        <input name="name" placeholder="请遵循Controller命名规则" class="span6"/>
                        <span>文件上传URL为&nbsp;<a href="javascript:void(0)"></a></span>
                    </div>
                </td>

            </tr>
            <!-- Now, the part can be involved in 'subdir_pattern'
            <tr>
                <td><span>上传路径</span></td>
                <td>
                    <div class="controls">
                        <input name="path" placeholder="文件最终保存路径" class="span6"/>
                    </div>
                </td>
            </tr>
            -->
            <tr>
                <td>文件名规则</td>
                <td>
                    <input type="text" name="filename_pattern" class="span6"/>
                    <br>
                    <span>可选规则：{date[`PHP date format`]}, {unix_timestamp}, {random[`min`, `max`]}, {md5}, {origin}</span>
                </td>
            </tr>

            <tr>
                <td>上传子路径规则</td>
                <td>
                    <input type="text" name="subdir_pattern" class="span6"/>
                    <br>
                    <span>可选规则：{date[`PHP date format`]}, {unix_timestamp}, {random[`min`, `max`]}</span>
                </td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <a class="btn green btn-build" overwrite="false">创建</a>
                    <a class="btn green btn-build-force" overwrite="true">创建(覆盖已有)</a>
                    <span></span>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
